version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: webcrawler-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: webcrawler
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: crawler_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "5432:5432"
    networks:
      - crawler-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crawler -d webcrawler"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local

# Networks
networks:
  crawler-network:
    driver: bridge