# Development Environment Configuration
# This configuration is optimized for local development and testing

# Database Configuration
database:
  host: localhost
  port: 5432
  name: webcrawler
  user: crawler
  password: ${DB_PASSWORD}
  pool_size: 5
  max_overflow: 10
  echo: false  # Set to true for SQL query logging

# Crawler Configuration
crawler:
  # Worker settings
  max_workers: 3
  max_depth: 2
  max_pages_per_domain: 100
  max_total_pages: 1000
  
  # Request settings
  delay_between_requests: 1.0
  request_timeout: 30
  max_retries: 3
  retry_delay: 2.0
  
  # User agent
  user_agent: "WebCrawler/1.0 (Development)"
  
  # Content filtering
  allowed_content_types:
    - "text/html"
    - "application/xhtml+xml"
    - "text/plain"
    - "text/xml"
    - "application/xml"
  
  # URL filtering
  blocked_extensions:
    - ".pdf"
    - ".doc"
    - ".docx"
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".gif"
    - ".mp3"
    - ".mp4"
    - ".zip"
    - ".exe"
  
  # Domain settings
  respect_robots_txt: true
  robots_cache_ttl: 3600  # 1 hour
  
  # Queue settings
  url_queue_size: 50000  # Increased for development to handle large sitemaps
  enable_bloom_filter: true

# Storage Configuration
storage:
  # Data directories
  data_dir: "./data"
  reports_dir: "./reports"
  profiles_dir: "./profiles"
  
  # File formats
  export_formats:
    - "json"
    - "csv"
    - "html"
  
  # Compression
  compress_data: false
  compression_level: 6

# Logging Configuration
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # File logging
  file:
    enabled: true
    path: "logs/crawler_dev.log"
    max_size: "10MB"
    backup_count: 5
    rotation: "time"  # or "size"
  
  # Console logging
  console:
    enabled: true
    level: INFO
  
  # JSON logging for structured logs
  json_logging: false
  
  # Logger levels for specific modules
  loggers:
    crawler.core: DEBUG
    crawler.content: DEBUG
    crawler.url_management: DEBUG
    crawler.monitoring: INFO
    crawler.reporting: INFO
    aiohttp: WARNING
    asyncpg: WARNING

# Monitoring Configuration
monitoring:
  enabled: true
  
  # Metrics collection
  metrics:
    enabled: true
    port: 8001
    host: "localhost"
    endpoint: "/metrics"
  
  # Performance profiling
  profiling:
    enabled: true
    sample_rate: 0.1  # 10% of requests
    output_dir: "profiles"
  
  # Health checks
  health_check:
    enabled: true
    port: 8002
    endpoint: "/health"
  
  # Resource monitoring
  resources:
    check_interval: 30  # seconds
    memory_threshold: 0.8  # 80% of available memory
    cpu_threshold: 0.8     # 80% CPU usage

# Content Analysis Configuration
content_analysis:
  # Text processing
  text_processing:
    min_text_length: 100
    max_text_length: 1000000
    remove_navigation: true
    clean_text: true
  
  # Word frequency analysis
  word_analysis:
    min_word_length: 2
    max_word_length: 50
    include_stopwords: false
    top_words_limit: 100
  
  # Language detection
  language_detection:
    enabled: true
    min_confidence: 0.8
  
  # Content quality scoring
  quality_scoring:
    enabled: true
    min_quality_score: 0.3

# URL Management Configuration
url_management:
  # Validation settings
  validation:
    max_url_length: 2048
    max_path_segments: 20
    max_query_params: 50
  
  # Canonicalization
  canonicalization:
    remove_fragments: true
    remove_empty_params: true
    sort_query_params: true
    lowercase_scheme_host: true
    remove_tracking_params: true
  
  # Rate limiting
  rate_limiting:
    default_delay: 1.0
    domain_delays: {}  # Custom delays per domain
    respect_crawl_delay: true

# Reporting Configuration
reporting:
  # Report generation
  generation:
    auto_generate: true
    formats: ["html", "json"]
    include_charts: true
    include_statistics: true
  
  # Data visualization
  visualization:
    chart_library: "plotly"  # or "matplotlib"
    theme: "light"
    max_data_points: 1000
  
  # Export settings
  export:
    compress_reports: false
    include_raw_data: true

# Security Configuration
security:
  # Request headers
  headers:
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    "Accept-Language": "en-US,en;q=0.5"
    "Accept-Encoding": "gzip, deflate"
    "DNT": "1"
    "Connection": "keep-alive"
    "Upgrade-Insecure-Requests": "1"
  
  # SSL/TLS settings
  ssl:
    verify_certificates: true
    ssl_context: null
  
  # Proxy settings (if needed)
  proxy:
    enabled: false
    http_proxy: null
    https_proxy: null

# Development-specific settings
development:
  # Debug features
  debug:
    save_raw_html: true
    save_request_logs: true
    verbose_errors: true
  
  # Testing
  testing:
    mock_requests: false
    test_data_dir: "tests/data"
    fixtures_dir: "tests/fixtures"
  
  # Hot reloading
  hot_reload: true
  
  # Development server
  dev_server:
    enabled: false
    port: 8000
    host: "localhost"